aleoapi:
    - "https://vm.aleo.org/api/testnet3"
    - "http://127.0.0.1/api/testnet3"
mysqldns: "mysql://root:1234567890@127.0.0.1:3306/aleo_blocks"
# 一次请求获取的区块数量
batch_request: 10
# 请求并发大小。获取区块数 = batch_concurrent * batch_request
batch_concurrent: 2
# 必须设置address，只记录address相关的区块或solution信息
address:
    - "aleo1wxkn9se2hxftwq0hcls4vwywy0pc8lc9xl97ws72yaca0zrflqzqcf20a0"
# 是否存储区块信息，默认false, 则只存储和address相关的solution信息
store_block: false
# api server
listen_ip: 0.0.0.0:9898