aleoapi:
    - "http://127.0.0.1:3033/testnet3"
    - "https://vm.aleo.org/api/testnet3"
mysqldsn: "mysql://root:1234567890@127.0.0.1:3306/aleo_blocks"
# 一次请求获取的区块数量
batch_request: 20
# 请求并发大小。获取区块数 = batch_concurrent * batch_request
batch_concurrent: 5
# 是否存储区块信息，默认true, 否则只存储solution信息
store_block: true
# address为空则记录所有（区块），solution信息
# address: 
# 或设置address，只记录address相关的（区块），solution信息
address:
    - "aleo1wxkn9se2hxftwq0hcls4vwywy0pc8lc9xl97ws72yaca0zrflqzqcf20a0"
# 记录当前已同步高度的文件路径
synced_height_file: "block_height.sync" 
# api server
listen_ip: "0.0.0.0:9898"